sudo: false

dist: trusty
addons:
    chrome: stable
before_install:
    - # start your web application and listen on `localhost`
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    ⋮

language: node_js

node_js:
    - "10"

git:
    submodules: false

before_script:
    - npm install

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov

notifications:
    webhooks:
        urls:
            # dbwebb-se/ramverk2
            - https://webhooks.gitter.im/e/04132ac4ce5f7823f96c
        on_success: change # options: [always|never|change] default: always
        on_failure: always # options: [always|never|change] default: always
        on_start: never # options: [always|never|change] default: always
