sudo: required
dist: trusty
addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable

language: node_js

node_js:
    - "10"

git:
    submodules: false

before_script:
    - npm install

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
